pipeline {
  agent any
  tools { 
        maven 'Maven-3.5.4'
        jdk 'JDK-8'
  }
  stages {
    stage('Clone repository') {
        /* Let's make sure we have the repository cloned to our workspace... */
      steps {
        checkout scm
      }
    }
    stage('Push image') {
      steps {
        withDockerRegistry([credentialsId: '00f24109-fda9-4fd9-9c13-c114877c04e4', url: "932864411704.dkr.ecr.us-east-1.amazonaws.com/mylab2"]) {
          sh '/usr/bin/docker tag httpd 932864411704.dkr.ecr.us-east-1.amazonaws.com/mylab2:latest'
          sh '/usr/bin/docker push 932864411704.dkr.ecr.us-east-1.amazonaws.com/mylab2:latest'
        }
      }
    }
  }
}
